### ISSUE TITLE
Migration to Smack 4.1.x

### ISSUE THREAD

**Issue by grigoryfedorov** [redsolution/xabber-android#502]
Here 4ac97c37d9217343f49095d512ad8383bc05e206 I have started migration to new version of Smack 4.1.0
https://github.com/igniterealtime/Smack

All libraries source code removed from project - gradle used.
It is very first working version - successfull build, account login, message sending.
Many things do not work so far, such as MUC, avatars, vcard, OTR, certificate problems, proxies, etc.
Some lines of code were commented out just to go away from build mistakes.

@aelmahmoudy you was interested in, as I remember)

Help welcomed!

**Comment by Flowdalic** [comment]
@grigoryfedorov great work!

Just a heads-up: I've just released Smack 4.1.3 a few days ago.

If you don't mind, I would offer to review the changes and help you with the migration. You are also invited to join #smack on freenode.

**Comment by grigoryfedorov** [comment]
@Flowdalic oh, that would be great! 
The main problems for me now located in the ConnectionThread https://github.com/redsolution/xabber-android/blob/feature/smack/app/src/main/java/com/xabber/android/data/connection/ConnectionThread.java

**Comment by aelmahmoudy** [comment]
@grigoryfedorov Are there still things that are not working ? Are proxies still not working ?

**Comment by grigoryfedorov** [comment]
@aelmahmoudy proxies is going to be fixed with next version of Smack. There are may be some minor or hidden problems, I expect them to be found and fixed after release of Beta or Dev version with new smack.

**Comment by Flowdalic** [comment]
@grigoryfedorov What is your Roadmap for Smack 4.(1|2) in xabber? Proxies are only fixed in Smack 4.2, which is not API compatible with 4.1 and will be likely released in ~6 months from now (with occasional -alpha/beta releases).

Will you
- Go with Smack 4.1?
- Create a branch for Smack 4.2?
- Do a combination of the above?

I personally would recommend getting a release with Smack 4.1 out, wait 1-2 months to fix issues, then branch off, switch to Smack 4.2 and continue development there while the stable smack-4.1 branch only gets bugfixes. Note that you can trigger me any time if you want a stable 4.2 -alpha/beta release to land in Maven Central.

**Comment by grigoryfedorov** [comment]
@Flowdalic I thought proxies would be releases sooner.. 
Also I thing about forking Smack and make use it as submodule, to get fixes faster or may be have ability to change Smack by myself. Smack master branch is for 4.2 with new API already?
Now I think, we could release Xabber Beta with Smack 4.1 (without proxies). And wait for reviews.

**Comment by Flowdalic** [comment]
> Also I thing about forking Smack and make use it as submodule, to get fixes faster or may be have ability to change Smack by myself.

In an ideal world, you wouldn't want to do that, because there is no need to do so. Either it's a (critical) non-API breaking bugfix changing Smack's internals, then it can go into a Smack patchlevel release, which are more often released, usually ~4-8 weeks, and even if not, you could use a fixed SNAPSHOT dependency in order to achieve reproduceable stable builds. Or it's a new feature, which you could always backport into Xabbers codebase and switch to the Smack version once you upgrade to the Smack release containing the feature.

Of course I can only suggest you not to establish your own flavor of Smack, because there is really no need to do so. For example Proxy support could also be done in Smack 4.1 using a custom Socket Factory. It's just way more cumbersome then using the native proxy support provided by Smack 4.2.

What you decide in the end is up to you. And no matter what you do, I'd be happy to help if my time allows it (and if you promise to upstream improvements :)).

**Comment by grigoryfedorov** [comment]
Closing this issue, since Smack 4.1 usage was merged to master. New issues should be created for specific problems with Smack version update. 
@Flowdalic thanks for help)
