### ISSUE TITLE
Cannot connect to ejabberd server

### ISSUE THREAD

**Issue by vanitasvitae** [redsolution/xabber-android#686]
Hi!
I built xabber myself from the latest develop branch (05c196ac7f8c31f032b5b9904060c09f5e6a39da).
When I try to connect to my server, the indicator states "connecting", but nothing happens. I have no srv record for my server, so I also tried the "custom server" option specifying the port, but no success either.

Here is a logcat:
````
03-02 23:08:21.292 12201 12201 D AccountItem: xabber@jabberhead.tk/Xabber_G4yl4tY8: connect
03-02 23:08:21.293 12201 12201 D AccountItem: xabber@jabberhead.tk/Xabber_G4yl4tY8: updateState. prev offline new connecting
03-02 23:08:21.293 12201 12201 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Connection thread is finished, creating new one...
03-02 23:08:21.293 12201 12201 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Creating new connection thread
03-02 23:08:21.293 12201 12201 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Connection thread is new, starting...
03-02 23:08:21.305 12201 14030 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Trying to connect and login...
03-02 23:08:21.308 12201 14030 D AccountItem: xabber@jabberhead.tk/Xabber_G4yl4tY8: updateState. prev connecting new connecting
03-02 23:08:21.310 12201 14030 D AndroidUsingExec: getDnsServerAddresses
03-02 23:08:21.331 12201 12201 D com.xabber.android.service.XabberService@61e06cd: changeForeground
03-02 23:08:21.333 12201 12201 D com.xabber.android.data.notification.NotificationManager@525794c: updatePersistentNotification account xabber@jabberhead.tk/Xabber_G4yl4tY8 state connecting
03-02 23:08:21.335 12201 12201 D com.xabber.android.data.notification.NotificationManager@525794c: Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
03-02 23:08:21.339  4712  4712 V NotificationService: pkg=com.xabber.android.beta canInterrupt=false intercept=true
03-02 23:08:21.345  4712  4712 V NotificationService: pkg=com.xabber.android.beta canInterrupt=false intercept=true
03-02 23:08:21.349 12201 14030 D de.measite.minidns.AbstractDNSClient: Asking /192.168.178.1 on 53 for _xmpp-client._tcp.jabberhead.tk.	IN	SRV with:
03-02 23:08:21.349 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(43879 QUERY NO_ERROR query[qr=0] rd)
03-02 23:08:21.349 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: _xmpp-client._tcp.jabberhead.tk.	IN	SRV]
03-02 23:08:21.349 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1024]
03-02 23:08:21.461 12201 14030 D de.measite.minidns.AbstractDNSClient: Response from /192.168.178.1 on 53 for _xmpp-client._tcp.jabberhead.tk.	IN	SRV:
03-02 23:08:21.461 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(43879 QUERY NX_DOMAIN resp[qr=1] rd ra)
03-02 23:08:21.461 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: _xmpp-client._tcp.jabberhead.tk.	IN	SRV]
03-02 23:08:21.461 12201 14030 D de.measite.minidns.AbstractDNSClient: [N: jabberhead.tk.	300	IN	SOA	ns01.freenom.com. soa.freenom.com. 1470922033 10800 3600 604800 3600]
03-02 23:08:21.461 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1460]
03-02 23:08:21.461 12201 14030 D org.jivesoftware.smack.util.DNSUtil: Could not resolve DNS SRV resource records for _xmpp-client._tcp.jabberhead.tk. Consider adding those.
03-02 23:08:21.463 12201 14030 D AndroidUsingExec: getDnsServerAddresses
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: Asking /192.168.178.1 on 53 for jabberhead.tk.	IN	A with:
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(3246 QUERY NO_ERROR query[qr=0] rd)
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	A]
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1024]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: Response from /192.168.178.1 on 53 for jabberhead.tk.	IN	A:
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(3246 QUERY NO_ERROR resp[qr=1] rd ra)
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	A]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [A: jabberhead.tk.	8046	IN	CNAME	vanitasvitae.no-ip.biz.]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [A: vanitasvitae.no-ip.biz.	8	IN	A	80.136.200.4]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1460]
03-02 23:08:21.515 12201 14030 D AndroidUsingExec: getDnsServerAddresses
03-02 23:08:21.542 12201 14030 D de.measite.minidns.AbstractDNSClient: Asking /192.168.178.1 on 53 for jabberhead.tk.	IN	AAAA with:
03-02 23:08:21.542 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(988 QUERY NO_ERROR query[qr=0] rd)
03-02 23:08:21.542 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	AAAA]
03-02 23:08:21.542 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1024]
03-02 23:08:21.550 12201 14030 D de.measite.minidns.AbstractDNSClient: Response from /192.168.178.1 on 53 for jabberhead.tk.	IN	AAAA:
03-02 23:08:21.550 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(988 QUERY NO_ERROR resp[qr=1] rd ra)
03-02 23:08:21.550 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	AAAA]
03-02 23:08:21.550 12201 14030 D de.measite.minidns.AbstractDNSClient: [A: jabberhead.tk.	8047	IN	CNAME	vanitasvitae.no-ip.biz.]
03-02 23:08:21.550 12201 14030 D de.measite.minidns.AbstractDNSClient: [N: no-ip.biz.	0	IN	SOA	nf1.no-ip.com. hostmaster.no-ip.com. 2152389753 600 300 604800 600]
03-02 23:08:21.550 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1460]
03-02 23:08:21.551 12201 14030 W System.err: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.jabberhead.tk:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.jabberhead.tk.	IN	SRV yielded an error response NX_DOMAIN
03-02 23:08:21.551 12201 14030 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:617)
03-02 23:08:21.551 12201 14030 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:888)
03-02 23:08:21.551 12201 14030 W System.err: 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:377)
03-02 23:08:21.551 12201 14030 W System.err: 	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(ConnectionThread.java:110)
03-02 23:08:21.552 12201 14030 W System.err: 	at com.xabber.android.data.connection.ConnectionThread$1.run(ConnectionThread.java:63)
03-02 23:08:21.552 12201 14030 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-02 23:08:21.553 12201 14030 W System.err: ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8
03-02 23:08:21.553 12201 14030 W System.err: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.jabberhead.tk:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.jabberhead.tk.	IN	SRV yielded an error response NX_DOMAIN
03-02 23:08:21.553 12201 14030 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:617)
03-02 23:08:21.553 12201 14030 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:888)
03-02 23:08:21.553 12201 14030 W System.err: 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:377)
03-02 23:08:21.553 12201 14030 W System.err: 	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(ConnectionThread.java:110)
03-02 23:08:21.553 12201 14030 W System.err: 	at com.xabber.android.data.connection.ConnectionThread$1.run(ConnectionThread.java:63)
03-02 23:08:21.553 12201 14030 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-02 23:08:21.553 12201 14030 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Connection thread finished
03-02 23:08:22.257 12201 12201 D AccountItem: xabber@jabberhead.tk/Xabber_G4yl4tY8: connect
03-02 23:08:22.258 12201 12201 D AccountItem: xabber@jabberhead.tk/Xabber_G4yl4tY8: updateState. prev connecting new connecting
03-02 23:08:22.258 12201 12201 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Connection thread is finished, creating new one...
03-02 23:08:22.258 12201 12201 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Creating new connection thread
03-02 23:08:22.258 12201 12201 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Connection thread is new, starting...
03-02 23:08:22.259 12201 12201 D ReconnectionManager: xabber@jabberhead.tk/Xabber_G4yl4tY8 not authenticated. new thread started. next attempt 1
03-02 23:08:22.263 12201 14036 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Trying to connect and login...
03-02 23:08:22.263 12201 14036 D AccountItem: xabber@jabberhead.tk/Xabber_G4yl4tY8: updateState. prev connecting new connecting
03-02 23:08:22.264 12201 14036 D AndroidUsingExec: getDnsServerAddresses
03-02 23:08:22.295 12201 14036 D de.measite.minidns.AbstractDNSClient: Asking /192.168.178.1 on 53 for _xmpp-client._tcp.jabberhead.tk.	IN	SRV with:
03-02 23:08:22.295 12201 14036 D de.measite.minidns.AbstractDNSClient: DNSMessage(34840 QUERY NO_ERROR query[qr=0] rd)
03-02 23:08:22.295 12201 14036 D de.measite.minidns.AbstractDNSClient: [Q: _xmpp-client._tcp.jabberhead.tk.	IN	SRV]
03-02 23:08:22.295 12201 14036 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1024]
03-02 23:08:22.310 12201 14036 D de.measite.minidns.AbstractDNSClient: Response from /192.168.178.1 on 53 for _xmpp-client._tcp.jabberhead.tk.	IN	SRV:
03-02 23:08:22.310 12201 14036 D de.measite.minidns.AbstractDNSClient: DNSMessage(34840 QUERY NX_DOMAIN resp[qr=1] rd ra)
03-02 23:08:22.310 12201 14036 D de.measite.minidns.AbstractDNSClient: [Q: _xmpp-client._tcp.jabberhead.tk.	IN	SRV]
03-02 23:08:22.310 12201 14036 D de.measite.minidns.AbstractDNSClient: [N: jabberhead.tk.	299	IN	SOA	ns01.freenom.com. soa.freenom.com. 1470922033 10800 3600 604800 3600]
03-02 23:08:22.310 12201 14036 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1460]
03-02 23:08:22.310 12201 14036 D org.jivesoftware.smack.util.DNSUtil: Could not resolve DNS SRV resource records for _xmpp-client._tcp.jabberhead.tk. Consider adding those.
03-02 23:08:22.311 12201 14036 D AndroidUsingExec: getDnsServerAddresses
03-02 23:08:22.341 12201 14036 D de.measite.minidns.AbstractDNSClient: Asking /192.168.178.1 on 53 for jabberhead.tk.	IN	A with:
03-02 23:08:22.341 12201 14036 D de.measite.minidns.AbstractDNSClient: DNSMessage(21994 QUERY NO_ERROR query[qr=0] rd)
03-02 23:08:22.341 12201 14036 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	A]
03-02 23:08:22.341 12201 14036 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1024]
03-02 23:08:22.348 12201 14036 D de.measite.minidns.AbstractDNSClient: Response from /192.168.178.1 on 53 for jabberhead.tk.	IN	A:
03-02 23:08:22.348 12201 14036 D de.measite.minidns.AbstractDNSClient: DNSMessage(21994 QUERY NO_ERROR resp[qr=1] rd ra)
03-02 23:08:22.348 12201 14036 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	A]
03-02 23:08:22.348 12201 14036 D de.measite.minidns.AbstractDNSClient: [A: jabberhead.tk.	8045	IN	CNAME	vanitasvitae.no-ip.biz.]
03-02 23:08:22.348 12201 14036 D de.measite.minidns.AbstractDNSClient: [A: vanitasvitae.no-ip.biz.	7	IN	A	80.136.200.4]
03-02 23:08:22.348 12201 14036 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1460]
03-02 23:08:22.350 12201 14036 D AndroidUsingExec: getDnsServerAddresses
03-02 23:08:22.378 12201 14036 D de.measite.minidns.AbstractDNSClient: Asking /192.168.178.1 on 53 for jabberhead.tk.	IN	AAAA with:
03-02 23:08:22.378 12201 14036 D de.measite.minidns.AbstractDNSClient: DNSMessage(15340 QUERY NO_ERROR query[qr=0] rd)
03-02 23:08:22.378 12201 14036 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	AAAA]
03-02 23:08:22.378 12201 14036 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1024]
03-02 23:08:22.386 12201 14036 D de.measite.minidns.AbstractDNSClient: Response from /192.168.178.1 on 53 for jabberhead.tk.	IN	AAAA:
03-02 23:08:22.386 12201 14036 D de.measite.minidns.AbstractDNSClient: DNSMessage(15340 QUERY NO_ERROR resp[qr=1] rd ra)
03-02 23:08:22.386 12201 14036 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	AAAA]
03-02 23:08:22.386 12201 14036 D de.measite.minidns.AbstractDNSClient: [A: jabberhead.tk.	8046	IN	CNAME	vanitasvitae.no-ip.biz.]
03-02 23:08:22.386 12201 14036 D de.measite.minidns.AbstractDNSClient: [N: no-ip.biz.	0	IN	SOA	nf1.no-ip.com. hostmaster.no-ip.com. 2152389753 600 300 604800 600]
03-02 23:08:22.386 12201 14036 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1460]
03-02 23:08:22.387 12201 14036 W System.err: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.jabberhead.tk:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.jabberhead.tk.	IN	SRV yielded an error response NX_DOMAIN
03-02 23:08:22.387 12201 14036 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:617)
03-02 23:08:22.387 12201 14036 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:888)
03-02 23:08:22.387 12201 14036 W System.err: 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:377)
03-02 23:08:22.387 12201 14036 W System.err: 	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(ConnectionThread.java:110)
03-02 23:08:22.387 12201 14036 W System.err: 	at com.xabber.android.data.connection.ConnectionThread$1.run(ConnectionThread.java:63)
03-02 23:08:22.387 12201 14036 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-02 23:08:22.388 12201 14036 W System.err: ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8
03-02 23:08:22.388 12201 14036 W System.err: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.jabberhead.tk:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.jabberhead.tk.	IN	SRV yielded an error response NX_DOMAIN
03-02 23:08:22.388 12201 14036 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:617)
03-02 23:08:22.388 12201 14036 W System.err: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:888)
03-02 23:08:22.388 12201 14036 W System.err: 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:377)
03-02 23:08:22.388 12201 14036 W System.err: 	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(ConnectionThread.java:110)
03-02 23:08:22.388 12201 14036 W System.err: 	at com.xabber.android.data.connection.ConnectionThread$1.run(ConnectionThread.java:63)
03-02 23:08:22.388 12201 14036 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-02 23:08:22.389 12201 14036 D ConnectionThread: xabber@jabberhead.tk/Xabber_G4yl4tY8: Connection thread finished
````

**Comment by casperklein** [comment]
I don't think it is related to missing SRV DNS records. I did a test on a server without these records and could connect without any problems.

fyi: Due a bug in MiniDNS (https://community.igniterealtime.org/thread/59872) the time to connect can take 15-20 seconds. Did you wait long enough?

Version: dev/1.0.155

**Comment by grigoryfedorov** [comment]
@casperklein this bug actually fixed in this Xabber version
@Flowdalic would be greate if you habe a look on this log.

**Comment by Flowdalic** [comment]
This is MiniDNS failing to follow the CNAME RR. (See https://github.com/rtreffer/minidns/issues/32)

```
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: Asking /192.168.178.1 on 53 for jabberhead.tk.	IN	A with:
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(3246 QUERY NO_ERROR query[qr=0] rd)
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	A]
03-02 23:08:21.488 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1024]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: Response from /192.168.178.1 on 53 for jabberhead.tk.	IN	A:
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: DNSMessage(3246 QUERY NO_ERROR resp[qr=1] rd ra)
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [Q: jabberhead.tk.	IN	A]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [A: jabberhead.tk.	8046	IN	CNAME	vanitasvitae.no-ip.biz.]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [A: vanitasvitae.no-ip.biz.	8	IN	A	80.136.200.4]
03-02 23:08:21.514 12201 14030 D de.measite.minidns.AbstractDNSClient: [X: EDNS: version: 0, flags:; udp: 1460]
```

**Comment by casperklein** [comment]
@grigoryfedorov fyi: I still have the connection delay in Version 1.0.155 (DNS times out when connecting to localhost:53). I thought you were aware of that, therefore I was patient and haven't open an issue for that ;-)

**Comment by andrewnenakhov** [comment]
All latest Xabber builds do connect to ejabberd servers, we test it all the time. Most likely if the issue still persists it has to be server setup. I'll close for now. If issue is still occurs, attach debug logs here.
