### ISSUE TITLE
[Bug] Messages are not added to chat after notification about message is clicked

### ISSUE THREAD

**Issue by VioLaDiDa** [redsolution/xabber-android#885]
Since update to Version 2.6.3 (602) on both Android 8 and now Android 9 (Sony Xperia XZ2 Compact) I have an issue with new messages not showing up in chat after I have received and clicked a notification in the notification tray. 

### Some Details:

- When I run xabber in the foreground and turn off the display: When I receive a notification about a new message, I unlock my phone and see no new message in the chat.

- When I run xabber in the background and turn off the display: When I receive a notification about a new message, I unlock my phone and see the notification in the tray, including the message itself, but when i click on the notification to switch to the chat, the message is not there.

- It happens usually with messages received shortly after locking the screen, but irrespective of when the notification is then read. 
- It also happens when not locking the Screen and xabber is in Background. 
- It happens usually with the first message if I have a notification of more than one new message, but also with single message notifications.

**Comment by bash-git** [comment]
Hi, 
I encountered the same error on my Moto G5. I checked the logfile an found at least two entry for a message which got lost. I found more Exceptions in the logfile but I have not verified all of them. 

2019-06-15_17-12-40 D/Smack﹕ RECV (0): <message from='<***fromUser***>' to='<***me***>' xml:lang='en' type='chat' id='<***id***>'><request xmlns='urn:xmpp:receipts'/><markable xmlns='urn:xmpp:chat-markers:0'/><origin-id xmlns='urn:xmpp:sid:0' id='<id>'/><active xmlns='http://jabber.org/protocol/chatstates'/><body>***</body></message>
2019-06-15_17-12-40 D/Smack﹕ RECV (0): <r xmlns='urn:xmpp:sm:3'/>
2019-06-15_17-12-40 D/Smack﹕ SENT (0): <a xmlns='urn:xmpp:sm:3' h='164'/>
2019-06-15_17-12-40 W/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41: f.b.c
	at f.d.a.j$a.a(Unknown Source:25)
	at f.e.b.a(Unknown Source:42)
	at f.e.c.a(Unknown Source:2)
	at f.d.a.h$a.e(Unknown Source:19)
	at f.d.a.h$a$1.call(Unknown Source:2)
	at f.d.c.f$1.call(Unknown Source:2)
	at f.d.c.b$a$2.call(Unknown Source:11)
	at f.d.c.g.run(Unknown Source:9)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.b.c
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.d.a.j$a.a(Unknown Source:25)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.e.b.a(Unknown Source:42)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.e.c.a(Unknown Source:2)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.d.a.h$a.e(Unknown Source:19)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.d.a.h$a$1.call(Unknown Source:2)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.d.c.f$1.call(Unknown Source:2)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.d.c.b$a$2.call(Unknown Source:11)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ f.d.c.g.run(Unknown Source:9)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-06-15_17-12-40 E/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ java.lang.Thread.run(Thread.java:764)
2019-06-15_17-12-40 D/com.xabber.android.data.message.BackpressureMessageSaver$2@955db41﹕ Exception is thrown. Created new publish subject.
2019-06-15_17-12-40 D/com.xabber.android.data.extension.otr.OTRManager@57f0c6b﹕ transform incoming message... ***
2019-06-15_17-12-40 D/com.xabber.android.data.extension.otr.OTRManager@57f0c6b﹕ Found session with id <***SESSIONID***> with status PLAINTEXT for user <***USER***>
2019-06-15_17-12-40 D/com.xabber.android.data.extension.otr.OTRManager@57f0c6b﹕ transformed incoming message: *** session status: PLAINTEXT

**Comment by casperklein** [comment]
I just expirienced the same. Samsung S10 (Android 9).

**Comment by andrewnenakhov** [comment]
@casperklein what was your android version? SHould be fixed in latest update.

**Comment by casperklein** [comment]
Android 9 (June Security Patch) & Xabber 2.6.3 (602).

Just noticed there was a Xabber update two days ago. Going to install that now :)
Thanks for fixing.

**Comment by shmibs** [comment]
my boyfriend says he's still seeing this bug on the latest 2.6.4

![android version](https://user-images.githubusercontent.com/2358713/63366434-99ef0080-c32e-11e9-8eaa-8f68b400ef03.png)

**Comment by andrewnenakhov** [comment]
@shmibs we didn't see this issue for quite a while. Anyway, our android developer had recently quit, so it'll be a while before we find a replacement... and funds to pay him. Our crowdfunding campaing is not exactly booming...

**Comment by shmibs** [comment]
understandable, yeh

♥
